Repository thoth-station/result-api, pull requests merged in 2018-10, with the labels that each got.

#77 Automatic update of dependency pytest from 3.8.1 to 3.8.2
  Pipfile.lock
Labels: bot

#79 Automatic update of dependency thoth-common from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot

#80 Automatic update of dependency thoth-common from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot

#81 Automatic update of dependency thoth-common from 0.3.8 to 0.3.9
  Pipfile.lock
Labels: bot

#83 Automatic update of dependency thoth-common from 0.3.10 to 0.3.11
  Pipfile.lock
Labels: bot

#85 Automatic update of dependency thoth-storages from 0.5.3 to 0.5.4
  Pipfile.lock
Labels: bot

#86 Automatic update of dependency pytest from 3.8.2 to 3.9.1
  Pipfile.lock
Labels: bot

#87 Automatic update of dependency autopep8 from 1.4 to 1.4.1
  Pipfile.lock
Labels: bot

#92 Automatic update of dependency thoth-storages from 0.5.4 to 0.6.0
  Pipfile.lock
Labels: bot

#93 Automatic update of dependency pytest from 3.9.1 to 3.9.2
  Pipfile.lock
Labels: bot

#94 Automatic update of dependency autopep8 from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: bot

#97 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#98 Automatic update of dependency thoth-common from 0.3.12 to 0.3.13
  Pipfile.lock
Labels: bot

#99 Automatic update of dependency thoth-common from 0.3.13 to 0.3.14
  Pipfile.lock
Labels: bot

#91 adding sentry and some minor cleanups
  .coafile
  .zuul.yaml
  README.rst
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  wsgi.py
Labels: approved, size/L

#103 Automatic update of dependency thoth-storages from 0.7.1 to 0.7.2
  Pipfile.lock
Labels: bot
