Repository thoth-station/result-api, pull requests merged in 2018-07, with the labels that each got.

#30 Automatic update of dependency thoth-storages from 0.0.32 to 0.0.33
  Pipfile.lock
Labels: approved, bot, size/XS

#33 Automatic update of dependency thoth-common from 0.0.9 to 0.1.0
  Pipfile.lock
Labels: bot

#41 Automatic update of dependency thoth-common from 0.1.0 to 0.2.0
  Pipfile.lock
Labels: bot

#44 Initial dependency lock
  Pipfile.lock
Labels: bot

#45 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#46 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#47 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#49 Adjust template labels
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
Labels: approved
