Repository thoth-station/result-api, pull requests merged in 2018-06, with the labels that each got.

#25 set resource limits of BC, DC
  CHANGELOG.md
  Jenkinsfile
  Pipfile.lock
  README.rst
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
Labels: approved, size/L

#26 Rename Template used by Jenkinsfile to `result-api-buildconfig`
  CHANGELOG.md
  Jenkinsfile
Labels: approved, size/S

#27 Rename THOTH_CEPH_HOST to THOTH_S3_ENDPOINT_URL
  openshift/deployment-template.yaml
Labels: approved, lgtm, size/XS

#29 Automatic update of dependency thoth-storages from 0.0.29 to 0.0.32
  Pipfile.lock
Labels: approved, bot, size/M
