Repository thoth-station/result-api, pull requests merged in 2018-08, with the labels that each got.

#50 Store adviser results
  wsgi.py
Labels: approved, size/XS

#51 Suppress annoying readiness/liveness logs
  wsgi.py
Labels: approved, size/XS

#52 Implement endpoints for provenance and adviser results
  wsgi.py
Labels: approved, size/S

#54 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XXL

#56 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot

#55 Automatic update of dependency pytest from 3.7.3 to 3.7.4
  Pipfile.lock
Labels: bot
