Repository thoth-station/result-api, pull requests merged in 2018-12, with the labels that each got.

#126 Automatic update of dependency thoth-storages from 0.9.0 to 0.9.3
  Pipfile.lock
Labels: bot

#127 API for subgraph checks
  wsgi.py
Labels: size/S

#129 Do not ask graph database for the core Python components
  wsgi.py
Labels: size/XS

#130 Automatic update of dependency thoth-common from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#131 Update thoth-storages not to break lib API
  Pipfile.lock
Labels: size/XS

#132 Automatic update of dependency pytest from 4.0.1 to 4.0.2
  Pipfile.lock
Labels: bot
