Repository thoth-station/result-api, pull requests merged in 2018-04, with the labels that each got.

#5 no s2i no namespace
  .gitignore
  .s2i/environment
  Jenkinsfile
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  wsgi.py
Labels: approved

#7 Cleanup
  Pipfile
  Pipfile.lock
  run.sh
Labels: approved

#9 Do not use Travis CI
  .travis.yml
Labels: approved

#10 Remove not relevant sentense from README
  README.rst
Labels: approved

#13 Remove thoth- prefix
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
Labels: approved, size/S

#14 License and license header
  LICENSE
  wsgi.py
Labels: approved, size/XL

#16 Remove unused volume/ dir
  volume/EMPTY
  volume/solver-84e44698-3490-405f-964d-d0237586d7c9.json
Labels: approved, size/XXL
