Repository thoth-station/result-api, pull requests merged in 2019-07, with the labels that each got.

#193 python black linting and styling fixes
  wsgi.py
Labels: approved, size/L

#195 Automatic update of dependency flask from 1.0.3 to 1.0.4
  Pipfile.lock
Labels: bot

#196 Automatic update of dependency flask from 1.0.4 to 1.1.0
  Pipfile.lock
Labels: bot

#197 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#199 Automatic update of dependency thoth-storages from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot

#194 updates to store buildlogs analysis result to ceph
  wsgi.py
Labels: approved, size/S

#201 Automatic update of dependency flask from 1.1.0 to 1.1.1
  Pipfile.lock
Labels: bot

#202 Automatic update of dependency thoth-storages from 0.14.4 to 0.14.5
  Pipfile.lock
Labels: bot

#203 Automatic update of dependency thoth-storages from 0.14.5 to 0.14.6
  Pipfile.lock
Labels: bot

#204 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#205 Automatic update of dependency thoth-storages from 0.14.6 to 0.14.7
  Pipfile.lock
Labels: bot

#206 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#207 Automatic update of dependency thoth-storages from 0.14.7 to 0.14.8
  Pipfile.lock
Labels: bot

#208 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#209 Automatic update of dependency thoth-storages from 0.14.8 to 0.15.0
  Pipfile.lock
Labels: bot

#210 Automatic update of dependency thoth-storages from 0.15.0 to 0.15.1
  Pipfile.lock
Labels: bot

#211 Automatic update of dependency thoth-storages from 0.15.1 to 0.15.2
  Pipfile.lock
Labels: bot

#213 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#216 Automatic update of dependency thoth-storages from 0.15.2 to 0.16.0
  Pipfile.lock
Labels: bot

#217 Automatic update of dependency thoth-storages from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot

#218 Automatic update of dependency thoth-storages from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: bot
