Repository thoth-station/result-api, pull requests merged in 2019-06, with the labels that each got.

#179 Automatic update of dependency pytest from 4.5.0 to 4.6.2
  Pipfile.lock
Labels: bot

#180 Provide configuration for Dgraph deployment
  openshift/deployment-template.yaml
Labels: approved, size/S

#181 Fix dgraph configuration in template
  openshift/deployment-template.yaml
Labels: approved, size/S

#178 Check if the given package in the given version was solved by specific solver
  wsgi.py
Labels: approved, size/XS

#182 Automatic update of dependency thoth-storages from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#183 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#184 Automatic update of dependency pytest from 4.6.2 to 4.6.3
  Pipfile.lock
Labels: bot

#185 Update the trigger-build job to use the latest job API
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#186 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#188 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#189 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot

#191 Automatic update of dependency thoth-storages from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#190 endpoint for package-analyzer is added
  wsgi.py
Labels: approved, size/S, size/XS

#192 Automatic update of dependency pytest from 4.6.3 to 5.0.0
  Pipfile.lock
Labels: bot
