Repository thoth-station/result-api, pull requests merged in 2019-10, with the labels that each got.

#253 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#255 Automatic update of dependency pytest-cov from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#257 Automatic update of dependency pytest-cov from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#258 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#254 Drop subgraph check endpoint
  wsgi.py
Labels: approved, size/S

#259 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#260 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#263 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#265 Increase requests
  openshift/deployment-template.yaml
Labels: approved, size/XS

#266 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#268 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#269 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
Labels: approved, size/S

#270 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#271 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
