Repository thoth-station/result-api, pull requests merged in 2019-08, with the labels that each got.

#219 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#220 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#200 Kebechet results
  Pipfile
  Pipfile.lock
  wsgi.py
Labels: approved, size/L, size/S

#221 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#222 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#224 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#225 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#226 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/XXL

#227 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XXL

#228 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#229 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#231 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#233 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#230 Kebechet conf
  .thoth.yaml
Labels: approved, size/S

#234 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
