Repository thoth-station/result-api, pull requests merged in 2019-09, with the labels that each got.

#232 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#236 Switch from Dgraph to PostgreSQL in deployment
  openshift/deployment-template.yaml
Labels: approved, size/M

#237 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#238 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#239 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#240 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#241 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#242 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#243 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#244 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#245 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#246 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#247 use postgresql hostname from thoth configmap
  openshift/deployment-template.yaml
Labels: approved, size/XS

#248 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#250 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#251 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot

#252 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot
