Repository thoth-station/result-api, pull requests merged in 2019-03, with the labels that each got.

#151 reworked the service account part
  .zuul.yaml
  openshift/deployment-template.yaml
Labels: approved, size/M

#152 Automatic update of dependency pytest from 4.3.0 to 4.3.1
  Pipfile.lock
Labels: bot

#153 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#155 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#156 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#157 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
