Repository thoth-station/result-api, pull requests merged in 2020-04, with the labels that each got.

#382 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/M

#383 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#384 Automatic update of dependency flask from 1.1.1 to 1.1.2
  Pipfile.lock
Labels: bot, size/M

#386 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/L

#387 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#388 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#389 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#390 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/L

#391 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#392 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/XS

#393 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/M

#394 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/S

#395 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
