Repository thoth-station/result-api, pull requests merged in 2020-05, with the labels that each got.

#398 added a service_version string
  __init__.py
  wsgi.py
Labels: size/M

#400 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#401 Release of version 0.7.2
  CHANGELOG.md
  __init__.py
Labels: bot, size/L

#406 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/L

#407 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/M

#408 Automatic update of dependency sentry-sdk from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot, size/M

#410 Release of version 0.7.3
  CHANGELOG.md
  __init__.py
Labels: bot, size/XS

#412 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/L

#414 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/M

#416 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#417 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#418 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/XS

#415 Release of version 0.7.4
  CHANGELOG.md
  __init__.py
Labels: bot, size/XS

#420 Release of version 0.7.5
  CHANGELOG.md
  version.py
Labels: bot, size/XS

#421 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/S

#422 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/S

#423 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/XS
