Repository thoth-station/result-api, pull requests merged in 2020-02, with the labels that each got.

#350 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#351 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#352 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#353 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#355 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/M

#354 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#356 Fallback to Pipfile.lock present in the repo on any Thoth error
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#357 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/M

#358 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/XS

#359 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#360 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#364 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/L

#365 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot, size/M

#366 Automatic update of dependency sentry-sdk from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot, size/XS

#367 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
